name: Build CI

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-2022 # 选择 Windows

    steps:
    - uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13' # 与本地一致

    - name: Install Conan
      run: pip install conan

    - name: Configure Conan Profile
      run: conan profile detect --force
      
    - name: Generate Key Pair for CI
      shell: bash # 强制使用 bash 以便在 Windows 上用 mkdir -p 和 openssl 命令
      run: |
        mkdir -p keyPair
        openssl genpkey -algorithm RSA -out keyPair/private.pem -pkeyopt rsa_keygen_bits:2048
        openssl rsa -pubout -in keyPair/private.pem -out keyPair/public.pem
    
    # 使用默认的官方 Conan Center
    - name: Build Project
      run: |
        cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug
        cmake --build build --config Debug

    - name: Upload Executable
      uses: actions/upload-artifact@v4
      with:
        name: service-exe
        path: build/bin/service.exe
